# Generated by Django 4.2 on 2023-05-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name="abonement",
            name="days",
            field=models.ManyToManyField(to="fitness_service.day"),
        ),
    ]
