# Generated by Django 4.2 on 2023-05-07 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_service", "0002_day_abonement_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abonement",
            name="isEven",
        ),
    ]
