# Generated by Django 4.2 on 2023-05-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness_service", "0004_day_exercise"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abonement",
            name="club",
        ),
        migrations.AddField(
            model_name="abonement",
            name="club",
            field=models.ManyToManyField(to="fitness_service.club"),
        ),
    ]
